version: '3.8'

services:
  nginx:
    build: ./srcs/nginx
    container_name: nginx
    ports:
      - "443:443"
    depends_on:
      - wordpress
    restart: always
    networks:
      - inception
    volumes:
      - wordpress_data:/var/www/html

  wordpress:
    build: ./srcs/wordpress
    container_name: wordpress
    depends_on:
      - mariadb
      - redis
    restart: always
    networks:
      - inception
    volumes:
      - wordpress_data:/var/www/html
    environment:
      - WORDPRESS_DB_HOST=mariadb
      - WORDPRESS_DB_USER=user
      - WORDPRESS_DB_PASSWORD=password
      - WORDPRESS_DB_NAME=wordpress

  mariadb:
    build: ./srcs/mariadb
    container_name: mariadb
    restart: always
    networks:
      - inception
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    networks:
      - inception

  ftp:
    build: ./srcs/ftp
    container_name: ftp
    restart: always
    networks:
      - inception

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    networks:
      - inception
    ports:
      - "8080:8080"

networks:
  inception:

volumes:
  wordpress_data:
  db_data:
